import type { CrmSnapshot } from "./types";

export const crmSeedData: CrmSnapshot = {
  leads: [
    {
      id: "crm-lead-1",
      name: "Maya Chen",
      email: "maya@northstarlabs.com",
      phone: "+1 415 555 0198",
      company: "Northstar Labs",
      title: "VP of Growth",
      companyId: "company-1",
      location: "San Francisco, CA",
      website: "https://northstarlabs.com",
      industry: "SaaS",
      socialProfiles: [
        { platform: "LinkedIn", url: "https://linkedin.com/in/mayachen" },
        { platform: "X", url: "https://x.com/mayachen" },
      ],
      stage: "Qualified",
      status: "Qualified",
      score: 94,
      priority: "High",
      aiSummary: "High-intent growth leader exploring AI-powered personalization and faster reply quality.",
      nextBestAction: "Send a tailored ROI case study and propose a 15-minute discovery call.",
      risk: "Low",
      opportunity: "Strong fit for expansion into multi-channel outbound automation.",
      tags: ["VP Growth", "High Intent", "Enterprise"],
      notes: "Interested in AI-assisted outreach for revenue teams.",
      createdAt: "2026-07-16",
      customFields: {
        region: "US West",
        source: "Inbound",
      },
    },
    {
      id: "crm-lead-2",
      name: "Owen Rivera",
      email: "owen@helio.ai",
      phone: "+1 212 555 0144",
      company: "Helio AI",
      title: "Revenue Operations Lead",
      companyId: "company-2",
      location: "New York, NY",
      website: "https://helio.ai",
      industry: "AI Infrastructure",
      socialProfiles: [{ platform: "LinkedIn", url: "https://linkedin.com/in/owenrivera" }],
      stage: "Meeting",
      status: "Contacted",
      score: 81,
      priority: "Medium",
      aiSummary: "Shows strong interest in sequencing and optimization workflows for sales teams.",
      nextBestAction: "Follow up with a product overview and pricing comparison sheet.",
      risk: "Medium",
      opportunity: "Opportunity to expand into a multi-step automation pilot.",
      tags: ["RevOps", "Pilot", "Mid-Market"],
      notes: "Asked for a short product overview and implementation timeline.",
      createdAt: "2026-07-20",
      customFields: {
        region: "East Coast",
        source: "CSV Import",
      },
    },
    {
      id: "crm-lead-3",
      name: "Rina Patel",
      email: "rina@latticeone.com",
      phone: "+44 20 7946 0123",
      company: "LatticeOne",
      title: "Head of Demand Gen",
      companyId: "company-3",
      location: "London, UK",
      website: "https://latticeone.com",
      industry: "Martech",
      socialProfiles: [{ platform: "LinkedIn", url: "https://linkedin.com/in/rinapatel" }],
      stage: "Prospecting",
      status: "New",
      score: 69,
      priority: "Low",
      aiSummary: "New lead with early interest in account-based messaging and conversion uplift.",
      nextBestAction: "Share a personalized cold intro email with a short case study excerpt.",
      risk: "Low",
      opportunity: "Potential for a high-value nurture campaign.",
      tags: ["Demand Gen", "UK"],
      notes: "Attended the product webinar last month.",
      createdAt: "2026-07-24",
      customFields: {
        region: "EMEA",
        source: "Referral",
      },
    },
  ],
  companies: [
    {
      id: "company-1",
      name: "Northstar Labs",
      overview: "B2B SaaS company focused on revenue operations and AI-enabled growth tools.",
      employeeCount: "201-500",
      industry: "SaaS",
      technologies: ["React", "Next.js", "Postgres", "Stripe"],
      funding: "$18M Series A",
      revenue: "$8M-$15M",
      location: "San Francisco, CA",
      website: "https://northstarlabs.com",
    },
    {
      id: "company-2",
      name: "Helio AI",
      overview: "AI infrastructure platform for automated workflows and verticalized copilots.",
      employeeCount: "51-200",
      industry: "AI Infrastructure",
      technologies: ["Python", "FastAPI", "Kafka", "AWS"],
      funding: "Bootstrapped",
      revenue: "$3M-$7M",
      location: "New York, NY",
      website: "https://helio.ai",
    },
    {
      id: "company-3",
      name: "LatticeOne",
      overview: "Martech platform specializing in lifecycle engagement and revenue orchestration.",
      industry: "Martech",
      technologies: ["Node.js", "TypeScript", "Snowflake"],
      funding: "$9M Seed",
      revenue: "$2M-$5M",
      employeeCount: "11-50",
      location: "London, UK",
      website: "https://latticeone.com",
    },
  ],
  tasks: [
    {
      id: "task-1",
      leadId: "crm-lead-1",
      title: "Prepare custom ROI deck",
      assignee: "Ava",
      dueDate: "2026-08-06",
      priority: "High",
      status: "In Progress",
    },
    {
      id: "task-2",
      leadId: "crm-lead-2",
      title: "Send pricing comparison",
      assignee: "Noah",
      dueDate: "2026-08-08",
      priority: "Medium",
      status: "Planned",
    },
  ],
  notes: [
    {
      id: "note-1",
      leadId: "crm-lead-1",
      title: "Discovery call prep",
      body: "Shared a tailored summary of the AI outreach workflow and requested a follow-up call.",
      mentions: ["Ava", "Maya"],
      attachments: ["ROI Deck.pdf"],
      createdAt: "2026-07-29",
    },
    {
      id: "note-2",
      leadId: "crm-lead-2",
      title: "Pilot interest",
      body: "Explored automation pilot design and emphasized speed to value.",
      mentions: ["Noah"],
      attachments: ["Pricing Sheet.pdf"],
      createdAt: "2026-07-28",
    },
  ],
  activities: [
    {
      id: "activity-1",
      leadId: "crm-lead-1",
      type: "Email",
      title: "Email sent",
      detail: "Sent tailored discovery email with AI workflow overview.",
      timestamp: "2h ago",
    },
    {
      id: "activity-2",
      leadId: "crm-lead-1",
      type: "Task",
      title: "Task created",
      detail: "Prepared custom ROI deck for follow-up call.",
      timestamp: "Today",
    },
    {
      id: "activity-3",
      leadId: "crm-lead-2",
      type: "Meeting",
      title: "Meeting booked",
      detail: "Discovery meeting scheduled for next week.",
      timestamp: "Yesterday",
    },
  ],
  pipelineStages: ["Prospecting", "Qualified", "Meeting", "Proposal", "Closed"],
};

export function getCrmSnapshot() {
  return crmSeedData;
}
